name: Generate Snake Animation

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    name: Gerar o GIF da Cobrinha
    runs-on: ubuntu-latest
    permissions:        # <-- CORREÇÃO: Permissão explícita de escrita
      contents: write   # <-- CORREÇÃO: Permissão explícita de escrita
    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v4
      
      # 2. Gera a Animação da Cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          # Seu username do GitHub
          github_user_name: Martinsz09 
          
          # Caminho onde o arquivo SVG será salvo
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # 3. Publica o SVG gerado na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # Branch onde a imagem será salva
          build_dir: dist       # Pasta onde a imagem foi gerada
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
